// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChDNHnaldeSlih9aYa7UhXlleNxGNKAXQ',
    appId: '1:69122893978:web:ceb64c6453eef00a329723',
    messagingSenderId: '69122893978',
    projectId: 'siscodb-23511',
    authDomain: 'siscodb-23511.firebaseapp.com',
    storageBucket: 'siscodb-23511.firebasestorage.app',
    measurementId: 'G-1PZLR0T0RH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi1UOtkkdx0vysEqroBOlROHehVSyV3bA',
    appId: '1:69122893978:android:0237c857274263ab329723',
    messagingSenderId: '69122893978',
    projectId: 'siscodb-23511',
    storageBucket: 'siscodb-23511.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRhWpeZNfUxHCvUvqoYFSDQlSWB8cVSeY',
    appId: '1:69122893978:ios:741dd5d4296b00e4329723',
    messagingSenderId: '69122893978',
    projectId: 'siscodb-23511',
    storageBucket: 'siscodb-23511.firebasestorage.app',
    iosBundleId: 'com.example.ciscoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRhWpeZNfUxHCvUvqoYFSDQlSWB8cVSeY',
    appId: '1:69122893978:ios:741dd5d4296b00e4329723',
    messagingSenderId: '69122893978',
    projectId: 'siscodb-23511',
    storageBucket: 'siscodb-23511.firebasestorage.app',
    iosBundleId: 'com.example.ciscoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChDNHnaldeSlih9aYa7UhXlleNxGNKAXQ',
    appId: '1:69122893978:web:38979c632fb7a0ba329723',
    messagingSenderId: '69122893978',
    projectId: 'siscodb-23511',
    authDomain: 'siscodb-23511.firebaseapp.com',
    storageBucket: 'siscodb-23511.firebasestorage.app',
    measurementId: 'G-YVF903C1XP',
  );
}
